config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'date'

class Cat < ApplicationRecord
  COLORS = [ 'orange', 'black', 'white', 'gray' ]
  validates :color, inclusion: { in: COLORS, message: "Color is not valid"}
  validates :sex, inclusion: { in: %w(M F), message: "Sex is not valid"}

  def age
    ((Date.today - self.birth_date).to_i)/365
  end

  has_many :requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: {in: %w( PENDING APPROVED DENIED)}
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest.where("start_date > ? AND start_date < ? OR end_date > ? AND end_date < ?",
    self.start_date, self.end_date, self.start_date, self.end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end
end

app/models/dummy.rb
class Dummy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    c = Cat.new(cat_parameters)
    if c.save
      redirect_to cats_url
    else
      render json: c.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_parameters)
      redirect_to cats_url
    else
      render json: @cat.errors.full_messages
    end
  end

  def cat_parameters
    params.require(:cat).permit(:name, :sex, :color, :description, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% prefix = (cat.persisted? ? cat_url(cat) : cats_url) %>
<form action=<%=prefix  %> method="post">
  <% unless cat.id %>
    <input type="hidden" name='_method' value="PATCH">
  <% end%>
  <input type="text" name="cat[name]" value=<%= cat.name %> >
  <label for="m"> Male</label>
  <input id="m" type="radio" name="cat[sex]" value = "M" <%= cat.sex=='M' ? 'checked="checked"' : "" %>>
  <label for="f"> Female</label>
  <input id="f" type="radio" name="cat[sex]" value="F" <%= cat.sex=='F' ? 'checked="checked"' : "" %>>
  <select name ="cat[color]">
    <option disabled <%= cat.color ? "" : "selected"%>>"Select a color"</option>
    <%Cat::COLORS.each do |color|  %>
      <option <%= cat.color == color ? "selected" : '' %> value= <%=color  %>>
        <%=color  %>
      </option>
    <% end %>
  </select>
  <input id='date' type='date' name='cat[birth_date]' value=<%= cat.birth_date %> >
  <textarea name='cat[description]'>
    <%=  cat.description%>
  </textarea>
  <input type="submit">
</form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <%= cat.name %>
  <%= link_to("Cat page", "cats/#{cat.id}") %> <br></br>
<% end %>

app/views/cats/new.html.erb
<%= render "form", cat: Cat.new %>

app/views/cats/show.html.erb
<table>
  <tr>
    <td>
<%= @cat.name %>
    </td>
  </tr>
  <tr>
    <td>
      <%= @cat.sex %>
    </td>
  </tr>
  <tr>
    <td>
<%= @cat.birth_date %>
    </td>
  </tr>
  <tr>
    <td>
<%= @cat.color %>
    </td>
  </tr>
  <tr>
    <td>
<%= @cat.description %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>